### ISSUE TITLE
Doesn't work on windows 8.1

### ISSUE THREAD

**Issue by gameplayoffert** [citizenfx/cfx-server-data#134]
Hi, i have tried to know why the ressource is not loaded and i have found the problem. The "Yarn" and the "Webpack" is nodejs ressource and i don't know why but can be downloaded and build only on windows 10 so do you have an idea why ? and how to solve it please ?

```log
Trace: 
  Error: write EIO
      at afterWriteDispatched (internal/stream_base_commons.js:150:25)
      at writeGeneric (internal/stream_base_commons.js:141:3)
      at WriteStream.Socket._writeGeneric (net.js:770:11)
      at WriteStream.Socket._write (net.js:782:8)
      at doWrite (_stream_writable.js:431:12)
      at writeOrBuffer (_stream_writable.js:415:5)
      at WriteStream.Writable.write (_stream_writable.js:305:11)
      at writeOnNthLine (D:\Server\resources\[system]\[builders]\yarn\yarn_cli.js:50249:12)
      at Spinner.render (D:\Server\resources\[system]\[builders]\yarn\yarn_cli.js:104572:48)
      at Spinner.start (D:\Server\resources\[system]\[builders]\yarn\yarn_cli.js:104562:10)
```

I know because i have installed the server on a new windows 10 computer.

**Comment by technetium-cfx** [comment]
Try changing your codepage by running `chcp 850` first. 

Why do you need the FiveM server to work on Windows 8.1 anyway?

**Comment by gameplayoffert** [comment]
first : thx for your answer and because my server is on my computer and my computer is on "windows 8.1" and i'm sorry but what is "chcp 850" and how can i run that before ?

**Comment by technetium-cfx** [comment]
You run it before starting you server. Please, this is not a support platform. I've told you multiple times to use the forums now.
